config/routes.rb
Rails.application.routes.draw do
  resources :players do
    resources :teams
  end
  
  resources :teams, only: [] do
    resources :games
  end

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :teams
    has_many :games
    has_many :stats
    
end

app/models/stat.rb
class Stat < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :player
    has_many :games    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :set_team
    before_action :set_player
    before_action :set_game, only: [:show, :edit, :update]
    
    def index
        @teams = @team.games
    end
  
    def show
        @game = Game.find(params[:id])
    end

    def new
        @game = @team.games.build
    end
    
    def create
        @game = @team.games.build(game_params)
        if @game.save
        redirect_to player_team_path(@player, @team), notice: "Game was successfully created."
        else
        render :new
        end
    end
    
    def edit
        @game = Game.find(params[:id])
    end
  
    def update
        @game = Game.find(params[:id])
        
        if @game.update(game_params)
            redirect_to player_team_path(@player, @team), notice: 'Game was successfully updated.'
        else
            render :edit
        end
    end

    private
    
    def set_team
        @team = Team.find(params[:team_id])
    end
    
    def set_game
        @game = @team.games.find(params[:id])
    end

    def set_player
        @player = @team.player  # Assuming Team model has a player association
      end
    
    def game_params
        params.require(:game).permit(:date, :opponent_team_name, :city, :is_victory, :is_home_team, :score, :opponent_score)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
      @players = Player.all
  end

  def show
  end

  def new
      @player = Player.new
  end

  def create
     @player = Player.new(player_params)
      if @player.save            
          redirect_to players_path, notice: "Player was added successfully"
      else
          render :new
      end
  end

  def edit
    @team = Team.find(params[:id])
    @player = @team.player
  end

  def update
      if @player.update(player_params)
          redirect_to players_path, notice: "Player was updated successfully"
      else
          render :edit
      end
  end

  def destroy
      @player.destroy
      redirect_to players_path, notice: "Player was deleted"
  end


  private

  def player_params
      params.require(:player).permit(:name)
  end

  def set_player
      @player = Player.find(params[:id])
  end  

end 

app/controllers/stats_controller.rb
class StatsController < ApplicationController
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    before_action :set_player
    ###before_action :set_team, only: [:show, :edit, :update, :destroy]

    def index
        @teams = @player.teams
    end
  
    def show
        @team = Team.find(params[:id])
        #@games = @team.games.order(date: :asc) # Fetch games sorted by date
    end
  
    def new
        @team = @player.teams.build
    end
  
    def create
       @team = @player.teams.build(team_params)
        if @team.save            
            redirect_to player_path(@player), notice: "Team was added successfully"
        else
            render :new
        end
    end
  
    def edit
        @team = Team.find(params[:id])
    end
  
    def update
        @team = Team.find(params[:id])
        
        if @team.update(team_params)
            redirect_to player_path(@player), notice: 'Team was successfully updated.'
        else
            render :edit
        end
    end
  ###
    ###def destroy
    ###    @team = Team.find(params[:id])
    ###    @team.destroy
    ###    redirect_to teams_url, notice: 'Team was successfully destroyed.'
    ###end
  
  
    private
   
    def set_player
        @player = Player.find(params[:player_id])
    end  

    def team_params
        params.require(:team).permit(:name, :year, :number)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.erb
<%= form_with(model: [@team, @game]) do |form| %>
  <%= render "shared/form_errors", form: form %>

    <div class="row">

      <div class="col-md-6">

        <div class="mb-3">
          <%= form.label :date %>
          <%= form.date_field :date, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :opponent_team_name %>
          <%= form.text_field :opponent_team_name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :city %>
          <%= form.text_field :city, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :is_home_team %>
          <%= form.check_box :is_home_team, class: "form-check-input" %>
        </div>

      </div>


      <div class="col-md-6">

        <div class="mb-3">
          <%= form.label :is_victory %>
          <%= form.check_box :is_victory, class: "form-check-input" %>
        </div>
        
        <div class="mb-3">
          <%= form.label :score %>
          <%= form.number_field :score, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :opponent_score %>
          <%= form.number_field :opponent_score, class: "form-control" %>
        </div>

      </div>

    </div>

  <%= form.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/games/edit.html.erb
<h1>Edit Game</h1>
<%= render 'form' %>
<%= link_to 'Back', team_game_path(@team, @game) %>

app/views/games/index.html.erb
<h1>Games</h1>

<%= link_to 'New Game', new_team_game_path(@team) %>

<% if @games.any? %>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Opponent Team Name</th>
        <th>City</th>
        <th>Is Victory</th>
        <th>Is Home Team</th>
        <th>Score</th>
        <th>Opponent Score</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= game.date %></td>
          <td><%= game.opponent_team_name %></td>
          <td><%= game.city %></td>
          <td><%= game.is_victory %></td>
          <td><%= game.is_home_team %></td>
          <td><%= game.score %></td>
          <td><%= game.opponent_score %></td>
          <td><%= link_to 'Show', team_game_path(@team, game) %></td>
          <td><%= link_to 'Edit', edit_team_game_path(@team, game) %></td>
          <td><%= link_to 'Destroy', team_game_path(@team, game), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No games found.</p>
<% end %>

<%= link_to 'Back', team_path(@team) %>

app/views/games/new.html.erb
<h1>Create Game</h1>
<%= render 'form' %>
<%= link_to "Back", player_team_path(@player, @team) %>

app/views/games/show.html.erb
<h1>Game Details</h1>

<p><strong>Date:</strong> <%= @game.date %></p>
<p><strong>Opponent Team Name:</strong> <%= @game.opponent_team_name %></p>
<p><strong>City:</strong> <%= @game.city %></p>
<p><strong>Is Victory:</strong> <%= @game.is_victory %></p>
<p><strong>Is Home Team:</strong> <%= @game.is_home_team %></p>
<p><strong>Score:</strong> <%= @game.score %></p>
<p><strong>Opponent Score:</strong> <%= @game.opponent_score %></p>

<%= link_to 'Edit', edit_team_game_path(@team, @game) %> |
<%= link_to 'Back', team_games_path(@team) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasketballStats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>

    <div class="container">      
      <%= render partial:"shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to Basketball Stats</h1>
</div>

app/views/players/_form.html.erb
<%= form_with model: player do |form| %>
    <%= render "shared/form_errors", form: form %>

    <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
    </div>

    <%= form.button "Save", class: "btn btn-primary", data: {turbo: "false"} %>

<% end %>

app/views/players/edit.html.erb
<h1>Edit Player</h1>
<%= render 'form', player: @player %>
<%= link_to 'Back', player_path(@player) %>

app/views/players/index.html.erb
<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Players</h1>
  </div>
  <% @players.each do |player| %>
    <div class="mb-3 card card-body">    
      <%= link_to player.name, player_path(player) %>
    </div>
  <% end %>
  <%= link_to "Add Player", new_player_path, class: "btn btn-primary" %>
</div>

app/views/players/new.html.erb
<h1>New Player</h1>
<%= render "form", player: @player %>
<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8">
      <h1><%= @player.name %></h1>
      <%= link_to 'Edit Player', edit_player_path(@player), class: "btn btn-info" %>
      
      <h2 class="mt-4">Teams</h2>
      <% if @player.teams.any? %>
        <ul class="list-group">
          <% @player.teams.each do |team| %>
            <li class="list-group-item">
              <%= link_to edit_player_team_path(@player, team), class: "btn btn-link" do %>
                <i class="bi bi-pencil-square"></i> <!-- Edit icon -->
              <% end %>              
              <%= link_to team.name, player_team_path(@player, team) %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>No teams found.</p>
      <% end %>

      <div class="mt-4">
        <%= link_to "Add a Team", new_player_team_path(@player), class: "btn btn-primary" %>
      </div>

    </div>
    <div class="col-md-4 text-end">
      <%= link_to 'Back', players_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
    <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Basketball Stats", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Players", players_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/stats/edit.html.erb
<h1>Edit Stat</h1>

app/views/stats/index.html.erb
<div class="d-flex justify-content-between align-items-center">
    <h1>Stats</h1>
</div>

app/views/stats/new.html.erb
<h1>Create Stat</h1>